events {
    worker_connections 1024;
}

http {

    proxy_connect_timeout 10s;
    proxy_send_timeout    30s;
    proxy_read_timeout    30s;

    server {
        listen 80;

        add_header Access-Control-Allow-Origin  "http://localhost:3000" always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

        if ($request_method = OPTIONS) {
            return 204;
        }

        # ── Pública ──────────────────────────────────────────
        location /api/auth/ {
            proxy_pass       http://usersapi:8080/auth/;
            proxy_set_header Host      $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ── Protegidas ───────────────────────────────────────
        location /api/users/ {
            proxy_pass       http://usersapi:8080/users/;
            proxy_set_header Host          $host;
            proxy_set_header X-Real-IP     $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/stock/ {
            proxy_pass       http://stockapi:8080/stock/;
            proxy_set_header Host          $host;
            proxy_set_header X-Real-IP     $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        # ── Rota não encontrada ──────────────────────────────
        location / {
            return 404 '{"error": "route not found"}';
            add_header Content-Type application/json;
        }
    }
}