@StockAPI_HostAddress = http://localhost:5003
@productId = REPLACE-WITH-CREATED-PRODUCT-ID
@orderId = 22222222-2222-2222-2222-222222222222
@otherOrderId = 33333333-3333-3333-3333-333333333333
@unknownProductId = 99999999-9999-9999-9999-999999999999

GET {{StockAPI_HostAddress}}/health
Accept: application/json

###

GET {{StockAPI_HostAddress}}/stock
Accept: application/json

###

POST {{StockAPI_HostAddress}}/stock
Content-Type: application/json

{
	"name": "Camiseta Dry Fit",
	"quantity": 20,
	"color": "Preto",
	"model": "Sport 2026",
	"size": "M",
	"costPrice": 39.90,
	"salePrice": 89.90
}

###

GET {{StockAPI_HostAddress}}/stock/{{productId}}
Accept: application/json

###

PUT {{StockAPI_HostAddress}}/stock/{{productId}}/reserve
Content-Type: application/json

{
	"orderId": "{{otherOrderId}}",
	"quantity": 3
}

###

PUT {{StockAPI_HostAddress}}/stock/{{productId}}/restock
Content-Type: application/json

{
	"quantity": 5
}

###

PUT {{StockAPI_HostAddress}}/stock/{{productId}}/reserve
Content-Type: application/json

{
	"orderId": "{{orderId}}",
	"quantity": 999
}

###

PUT {{StockAPI_HostAddress}}/stock/{{productId}}/release
Content-Type: application/json

{
	"orderId": "{{orderId}}",
	"quantity": 2
}

###

PUT {{StockAPI_HostAddress}}/stock/{{productId}}/confirm
Content-Type: application/json

{
	"orderId": "{{orderId}}",
	"quantity": 2
}

###

GET {{StockAPI_HostAddress}}/stock/{{productId}}/history
Accept: application/json

###

GET {{StockAPI_HostAddress}}/stock/{{unknownProductId}}
Accept: application/json

###

PUT {{StockAPI_HostAddress}}/stock/{{unknownProductId}}/reserve
Content-Type: application/json

{
	"orderId": "{{orderId}}",
	"quantity": 1
}

###
